export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_PRODUCT = "SET_PRODUCT";
export const FETCH_ERROR = "FETCH_ERROR";
export const PRODUCT_ID_DOES_NOT_EXIST_ERROR =
  "PRODUCT_ID_DOES_NOT_EXIST_ERROR";

export const SET_LOADING = "SET_LOADING";
export const SET_LATEST_DOC = "SET_LATEST_DOC";
